const products = [
  {
    title: "Ghế Nhựa Màu Trắng",
    description: "Ghế nhựa hiện đại với thiết kế tối giản, phù hợp cho phòng ăn hay không gian làm việc. Chất liệu nhựa bền bỉ, dễ vệ sinh và có khả năng chịu lực tốt.",
    price: 600000,
    stock: 50,
    discountPercentValue: 90,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664825863/file-Auffur/tmp-7-1664825837451_wwssvi.png",
    categories: {
      "Danh mục nổi bật": ["Ưu đãi đơn hàng đầu tiên"],
      "Vị trí": ["Phòng ăn"],
      "Tính năng": ["Ghế"],
      "Khác": [],
    },
  },
  {
    title: "Bộ Bàn Ghế Ăn Màu Nâu",
    description: "Bộ bàn ghế ăn cao cấp với thiết kế sang trọng, gỗ tự nhiên chất lượng cao. Thích hợp cho không gian phòng ăn hoặc phòng khách gia đình.",
    price: 6000000,
    stock: 50,
    discountPercentValue: 15,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1666438205/file-Auffur/tmp-1-1666438198442_v4trpy.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật", "Giảm giá"],
      "Vị trí": ["Phòng ăn"],
      "Tính năng": ["Ghế", "Bàn", "Bộ"],
      "Khác": [],
    },
  },
  {
    title: "Bàn Gỗ Tự Nhiên",
    description: "Bàn gỗ cao cấp với bề mặt nhẵn mịn, thiết kế tinh tế. Được làm từ gỗ tự nhiên nguyên chất, bền vững và có tính thẩm mỹ cao.",
    price: 3000000,
    stock: 50,
    discountPercentValue: 45,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664790450/file-Auffur/tmp-1-1664790412592_pogleh.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật", "Giảm giá", "Ưu đãi đơn hàng đầu tiên"],
      "Vị trí": ["Phòng bếp"],
      "Tính năng": ["Bộ", "Bàn"],
      "Khác": [],
    },
  },
  {
    title: "Ghế Dài Màu Nâu",
    description: "Ghế dài thoải mái với thiết kế hiện đại, phù hợp cho phòng khách. Chất liệu vải đệm mềm mại, có đủ chỗ cho cả gia đình.",
    price: 1440000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664811391/file-Auffur/tmp-1-1664811267215_li5isp.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Phòng khách"],
      "Tính năng": ["Ghế", "Sofa"],
      "Khác": [],
    },
  },
  {
    title: "Bàn Phụ Trang Trí",
    description: "Bàn phụ nhỏ gọn với thiết kế trang trí, phù hợp để đặt cạnh sofa hoặc góc phòng. Có tính năng lưu trữ thêm.",
    price: 480000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664812297/file-Auffur/tmp-1-1664812284938_kyonay.png",
    categories: {
      "Danh mục nổi bật": [],
      "Vị trí": [],
      "Tính năng": ["Bàn", "Sofa"],
      "Khác": [],
    },
  },
  {
    title: "Bàn Quầy",
    description: "Bàn quầy cao phù hợp cho không gian bếp hoặc bar. Thiết kế hiện đại với chất liệu bền bỉ, dễ lau chùi.",
    price: 576000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664812647/file-Auffur/tmp-2-1664812645086_apkgpw.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Văn phòng"],
      "Tính năng": [],
      "Khác": [],
    },
  },
  {
    title: "Ghế Văn Phòng Màu Nâu",
    description: "Ghế văn phòng ergonomic với thiết kế thoải mái, hỗ trợ lưng tốt. Chất liệu cao cấp, phù hợp cho không gian làm việc chuyên nghiệp.",
    price: 1440000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664812832/file-Auffur/tmp-3-1664812801104_kiu2og.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Văn phòng"],
      "Tính năng": ["Ghế"],
      "Khác": [],
    },
  },
  {
    title: "Bộ Bàn Ăn Gỗ",
    description: "Bộ bàn ăn đầy đủ gồm bàn và ghế, thiết kế vợng tròn tinh tế. Chất liệu gỗ cao cấp, thích hợp cho gia đình lớn.",
    price: 3840000,
    stock: 50,
    discountPercentValue: 10,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664812972/file-Auffur/tmp-4-1664812867715_t02ggj.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Phòng ăn"],
      "Tính năng": ["Bàn", "Ghế"],
      "Khác": [],
    },
  },
  {
    title: "Tủ Bàn Gỗ Phòng Bếp",
    description: "Tủ bàn gỗ đa năng với không gian lưu trữ rộng rãi. Thiết kế tối giản nhưng đầy tính thực dụng cho phòng bếp.",
    price: 960000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813327/file-Auffur/tmp-6-1664813318091_jtglsl.png",
    categories: {
      "Danh mục nổi bật": [],
      "Vị trí": ["Phòng bếp"],
      "Tính năng": ["Bàn", "Tủ"],
      "Khác": [],
    },
  },
  {
    title: "Ghế Văn Phòng Xám",
    description: "Ghế văn phòng màu xám hiện đại với độ nệm mềm thoải mái. Hỗ trợ lưng tốt, phù hợp cho làm việc lâu trong ngày.",
    price: 1200000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813292/file-Auffur/tmp-5-1664813215573_gj8z5b.png",
    categories: {
      "Danh mục nổi bật": [],
      "Vị trí": ["Văn phòng"],
      "Tính năng": [],
      "Khác": [],
    },
  },
  {
    title: "Ghế Bé Em Trang Trí",
    description: "Ghế bé em với màu sắc trang trí, an toàn cho trẻ em. Chất liệu vừa vặn, phù hợp cho phòng của bé hoặc không gian vui chơi.",
    price: 360000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813469/file-Auffur/tmp-7-1664813455534_st9usg.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật", "Ưu đãi đơn hàng đầu tiên"],
      "Vị trí": ["Văn phòng"],
      "Tính năng": ["Ghế"],
      "Khác": ["Dành cho trẻ em"],
    },
  },
  {
    title: "Ghế Ăn Trắng",
    description: "Ghế ăn màu trắng thanh lịch với thiết kế hiện đại. Phù hợp cho không gian phòng ăn hay văn phòng, dễ dàng kết hợp với các nội thất khác.",
    price: 384000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813573/file-Auffur/tmp-8-1664813568107_moraqd.png",
    categories: {
      "Danh mục nổi bật": [],
      "Vị trí": ["Phòng ăn"],
      "Tính năng": ["Ghế"],
      "Khác": [],
    },
  },
  {
    title: "Ghế Trang Trí",
    description: "Ghế trang trí với thiết kế độc đáo, màu sắc nổi bật. Phù hợp để làm điểm nhấn trong phòng khách hoặc phòng ngủ.",
    price: 720000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813774/file-Auffur/tmp-9-1664813725670_id5hls.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Phòng khách"],
      "Tính năng": ["Ghế"],
      "Khác": [],
    },
  },
  {
    title: "Ghế Dài Đỏ",
    description: "Ghế dài màu đỏ với thiết kế sang trọng, chất liệu vải cao cấp. Thích hợp để tạo điểm nhấn màu sắc cho phòng khách.",
    price: 1680000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664814578/file-Auffur/tmp-14-1664814568390_wo92xf.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Phòng khách"],
      "Tính năng": ["Ghế", "Sofa"],
      "Khác": [],
    },
  },
  {
    title: "Ghế Văn Phòng Da",
    description: "Ghế văn phòng bằng da cao cấp với gối đầu tháo rời. Thiết kế chuyên nghiệp, phù hợp cho không gian làm việc cao cấp.",
    price: 1320000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664814124/file-Auffur/tmp-12-1664814073016_qxaoqr.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Văn phòng"],
      "Tính năng": ["Ghế"],
      "Khác": [],
    },
  },
  {
    title: "Ghế Tay Vàng",
    description: "Ghế tay vàng với thiết kế nhã nhặn, chất liệu vải thoải mái. Phù hợp cho phòng khách, phòng ngủ hoặc không gian nghỉ ngơi.",
    price: 768000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813947/file-Auffur/tmp-11-1664813939182_yxvy2r.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Phòng khách", "Phòng ngủ"],
      "Tính năng": ["Ghế", "Sofa"],
      "Khác": [],
    },
  },
  {
    title: "Đèn Trang Trí Vàng",
    description: "Đèn trang trí vàng với thiết kế hiện đại, ánh sáng ấm áp. Thích hợp để chiếu sáng và trang trí cho phòng khách hoặc phòng ngủ.",
    price: 528000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813904/file-Auffur/tmp-10-1664813793825_qhdb2x.png",
    categories: {
      "Danh mục nổi bật": ["Ưu đãi đơn hàng đầu tiên"],
      "Vị trí": ["Phòng khách", "Phòng ngủ"],
      "Tính năng": ["Đèn"],
      "Khác": [],
    },
  },
  {
    title: "Tủ Đầu Giường",
    description: "Tủ đầu giường gỗ với không gian lưu trữ tiện dụng. Thiết kế tinh tế, phù hợp cho phòng ngủ hiện đại.",
    price: 648000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664823309/file-Auffur/tmp-3-1664823271478_bev2ag.png",
    categories: {
      "Danh mục nổi bật": ["Ưu đãi đơn hàng đầu tiên"],
      "Vị trí": ["Phòng bếp"],
      "Tính năng": ["Tủ"],
      "Khác": [],
    },
  },
  {
    title: "Xay Tiêu Màu Đen",
    description: "Xay tiêu chuyên dụng với cơ chế xay mịn, chất liệu thép không gỉ. Thích hợp cho nhà bếp, giúp xay gia vị một cách hiệu quả.",
    price: 120000,
    stock: 50,
    discountPercentValue: 80,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664813904/file-Auffur/tmp-10-1664813793825_qhdb2x.png",
    categories: {
      "Danh mục nổi bật": ["Ưu đãi đơn hàng đầu tiên"],
      "Vị trí": ["Phòng bếp"],
      "Tính năng": [],
      "Khác": [],
    },
  },
  {
    title: "Ghế Dài Xám",
    description: "Ghế dài xám hiện đại với đệm mềm thoải mái. Phù hợp cho phòng khách rộng rãi, có độ bền cao.",
    price: 1824000,
    stock: 50,
    discountPercentValue: 80,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664824771/file-Auffur/tmp-4-1664824711615_fe2nbg.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Phòng khách"],
      "Tính năng": ["Ghế", "Sofa"],
      "Khác": [],
    },
  },
  {
    title: "Không Gian Làm Việc Đa Người",
    description: "Bộ không gian làm việc đa người với bàn và ghế hiện đại. Thiết kế tối ưu hóa cho không gian văn phòng, hỗ trợ nhiều người làm việc cùng lúc.",
    price: 12000000,
    stock: 50,
    discountPercentValue: 80,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664824951/file-Auffur/tmp-5-1664824933677_m9pu0j.png",
    categories: {
      "Danh mục nổi bật": ["Nổi bật"],
      "Vị trí": ["Văn phòng"],
      "Tính năng": ["Ghế", "Bàn", "Bộ"],
      "Khác": [],
    },
  },
  {
    title: "Giường Gỗ",
    description: "Giường gỗ cao cấp với kết cấu chắc chắn, thiết kế trang trí tinh tế. Phù hợp cho phòng ngủ hiện đại, mang lại cảm giác ấm áp và thoải mái.",
    price: 1608000,
    stock: 50,
    discountPercentValue: 0,
    image: "https://res.cloudinary.com/dej0cuctl/image/upload/v1664825314/file-Auffur/tmp-6-1664825306530_tgylqm.png",
    categories: {
      "Danh mục nổi bật": [],
      "Vị trí": ["Phòng ngủ"],
      "Tính năng": [],
      "Khác": [],
    },
  },
];

module.exports = products;
